sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx update
- echo 'y' | sfdx plugins:install sfdx-git-delta
jobs:
  include:
    - stage: Deploy to DEV
      name: "Authorize the Org"
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
      name: "Get the Delta"
    - # stage name not required, will continue to use `test`
      script: ./test 2
      name: "Deploy to Target Org"
    - stage: Deploy to QA
      script: ./deploy